
  
 


  


  DecompressionStream
  
  ClipboardItem
  CanvasCaptureMediaStreamTrack
  BlobEvent
  BeforeInstallPromptEvent

  XPathResult
  XPathExpression
  XPathEvaluator

  VTTCue
  TreeWalker
  TransitionEvent

  TextEvent
  TaskAttributionTiming
  SubmitEvent
  StyleSheetList
  StyleSheet
  StylePropertyMapReadOnly
  StylePropertyMap
  StaticRange
  Selection
  SecurityPolicyViolationEvent

  ResizeObserverEntry
  ResizeObserver
  ReportingObserver
  


  NamedNodeMap
  MutationRecord
  MutationObserver
  
  MediaQueryListEvent
  MediaQueryList
  MediaList
  LayoutShift
  LargestContentfulPaint
  KeyframeEffect
  IntersectionObserverEntry
  IntersectionObserver
  InputDeviceCapabilities
  IdleDeadline
  Headers

  FormData
  FontFaceSetLoadEvent
  FontFace
  FileReader
  FileList
  File
  ElementInternals
  
  
  Blob
  AnimationEvent
  AnimationEffect
  Animation
  AbortSignal
  AbortController
  WebKitCSSMatrix
  WebKitMutationObserver
  parent
  opener
  top
  length
  frames
  closed
  location
  self
  window
  document
  name
  customElements
  locationbar
  menubar
  personalbar
  scrollbars
  statusbar
  toolbar
  status
  origin
  external
 

  devicePixelRatio
  clientInformation
  event
  offscreenBuffering
 
  defaultStatus
  defaultstatus
  styleMedia
  isSecureContext
  stop
  open
  confirm
  prompt
  print
  queueMicrotask
  requestAnimationFrame
  cancelAnimationFrame
  captureEvents
  releaseEvents
  requestIdleCallback
  cancelIdleCallback
  getComputedStyle
  matchMedia

  getSelection
  find


  createImageBitmap
 
  postMessage
  crypto
  indexedDB
  sessionStorage
  localStorage
  chrome
  WebAssembly
  FragmentDirective
  FeaturePolicy
  UserActivation
  XSLTProcessor
  BackgroundFetchManager
  BackgroundFetchRecord
  BackgroundFetchRegistration
  MediaMetadata
  MediaSession
  MediaSource
  Notification

  PeriodicSyncManager
  Permissions
  PermissionStatus
  EnterPictureInPictureEvent
  PictureInPictureWindow
  PushManager
  PushSubscription
  PushSubscriptionOptions
  RemotePlayback
  SpeechSynthesisErrorEvent
  SpeechSynthesisEvent
  SpeechSynthesisUtterance
  VideoPlaybackQuality
  BluetoothUUID
  speechSynthesis
  openDatabase
  trustedTypes
  applicationCache
  Worklet
  TrustedHTML
  TrustedScript
  TrustedScriptURL
  TrustedTypePolicy
  TrustedTypePolicyFactory
  ApplicationCacheErrorEvent
  caches
  AbsoluteOrientationSensor
  Accelerometer
  Cache
  CacheStorage
  Clipboard
  Credential
  CredentialsContainer
  CryptoKey
  DeviceMotionEvent
  DeviceMotionEventAcceleration
  DeviceMotionEventRotationRate
  DeviceOrientationEvent
  FederatedCredential
  Gyroscope
 
  LinearAccelerationSensor
  Lock
  LockManager
  MediaDeviceInfo
  MediaDevices
  MediaKeyMessageEvent
  MediaKeys
  MediaKeySession
  MediaKeyStatusMap
  MediaKeySystemAccess
  MIDIAccess
  MIDIConnectionEvent
  MIDIInput
  MIDIInputMap
  MIDIMessageEvent
  MIDIOutput
  MIDIOutputMap
  MIDIPort
  NavigationPreloadManager
  OrientationSensor
  PasswordCredential
  RelativeOrientationSensor
  RTCIceTransport
  Sensor
  SensorErrorEvent
  ServiceWorker
  ServiceWorkerContainer
  ServiceWorkerRegistration
  StorageManager
  SubtleCrypto
  XRDOMOverlayState
  BarcodeDetector

  Presentation
  PresentationAvailability
  PresentationConnection
  PresentationConnectionAvailableEvent
  PresentationConnectionCloseEvent
  PresentationConnectionList
  PresentationReceiver
  PresentationRequest
  AuthenticatorAssertionResponse
  AuthenticatorAttestationResponse
  AuthenticatorResponse
  PublicKeyCredential

  
  XRBoundedReferenceSpace
  XRFrame
  XRInputSource
  XRInputSourceArray
  XRInputSourceEvent
  XRInputSourcesChangeEvent
  XRPose
  XRReferenceSpace
  XRReferenceSpaceEvent
  XRRenderState
  XRRigidTransform
  XRSession
  XRSessionEvent
  XRSpace
  XRSystem
  XRView
  XRViewerPose
  XRViewport
  XRWebGLLayer
  XRHitTestResult
  XRHitTestSource
  XRRay
  XRTransientInputHitTestResult
  XRTransientInputHitTestSource
  filterOut

